FROM openjdk:8-jre-alpine
COPY ./target/cricket-score-service-0.0.1-SNAPSHOT.jar target/cricket-score-service-0.0.1-SNAPSHOT.jar
WORKDIR target/
ENTRYPOINT ["java", "-jar", "cricket-score-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080